#!/bin/bash
#
# Verify Certificates Generated by Enclave
# This script verifies that all certificates are properly signed by the enclave Root CA
#

set -e

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT_CA_CERT="$PROJECT_DIR/enclave-data/root-ca.crt"
ORGANIZATIONS_DIR="$PROJECT_DIR/organizations"

echo "======================================================================"
echo "Verifying Fabric Certificates"
echo "======================================================================"

if [ ! -f "$ROOT_CA_CERT" ]; then
    echo "❌ Root CA certificate not found: $ROOT_CA_CERT"
    echo "   Run: ./init_enclave_ca.sh"
    exit 1
fi

echo "✓ Root CA certificate found"
echo ""

# Function to verify a certificate
verify_cert() {
    local cert_path=$1
    local cert_name=$2

    if [ ! -f "$cert_path" ]; then
        echo "  ⚠ Not found: $cert_name"
        return 1
    fi

    # Verify certificate is signed by Root CA
    if openssl verify -CAfile "$ROOT_CA_CERT" "$cert_path" > /dev/null 2>&1; then
        echo "  ✓ Valid: $cert_name"
        return 0
    else
        echo "  ❌ Invalid: $cert_name (not signed by Root CA)"
        return 1
    fi
}

total_certs=0
valid_certs=0

echo "Verifying Hot Chain Orderer Certificates:"
verify_cert "$ORGANIZATIONS_DIR/ordererOrganizations/hot.coc.com/orderers/orderer.hot.coc.com/msp/signcerts/cert.pem" "orderer.hot.coc.com signing cert"
[ $? -eq 0 ] && ((valid_certs++))
((total_certs++))

verify_cert "$ORGANIZATIONS_DIR/ordererOrganizations/hot.coc.com/orderers/orderer.hot.coc.com/tls/server.crt" "orderer.hot.coc.com TLS cert"
[ $? -eq 0 ] && ((valid_certs++))
((total_certs++))

echo ""
echo "Verifying Cold Chain Orderer Certificates:"
verify_cert "$ORGANIZATIONS_DIR/ordererOrganizations/cold.coc.com/orderers/orderer.cold.coc.com/msp/signcerts/cert.pem" "orderer.cold.coc.com signing cert"
[ $? -eq 0 ] && ((valid_certs++))
((total_certs++))

verify_cert "$ORGANIZATIONS_DIR/ordererOrganizations/cold.coc.com/orderers/orderer.cold.coc.com/tls/server.crt" "orderer.cold.coc.com TLS cert"
[ $? -eq 0 ] && ((valid_certs++))
((total_certs++))

echo ""
echo "Verifying LawEnforcement Peer Certificates:"
verify_cert "$ORGANIZATIONS_DIR/peerOrganizations/lawenforcement.hot.coc.com/peers/peer0.lawenforcement.hot.coc.com/msp/signcerts/cert.pem" "peer0.lawenforcement signing cert"
[ $? -eq 0 ] && ((valid_certs++))
((total_certs++))

verify_cert "$ORGANIZATIONS_DIR/peerOrganizations/lawenforcement.hot.coc.com/peers/peer0.lawenforcement.hot.coc.com/tls/server.crt" "peer0.lawenforcement TLS cert"
[ $? -eq 0 ] && ((valid_certs++))
((total_certs++))

verify_cert "$ORGANIZATIONS_DIR/peerOrganizations/lawenforcement.hot.coc.com/users/Admin@lawenforcement.hot.coc.com/msp/signcerts/cert.pem" "Admin@lawenforcement"
[ $? -eq 0 ] && ((valid_certs++))
((total_certs++))

echo ""
echo "Verifying ForensicLab Peer Certificates:"
verify_cert "$ORGANIZATIONS_DIR/peerOrganizations/forensiclab.hot.coc.com/peers/peer0.forensiclab.hot.coc.com/msp/signcerts/cert.pem" "peer0.forensiclab signing cert"
[ $? -eq 0 ] && ((valid_certs++))
((total_certs++))

verify_cert "$ORGANIZATIONS_DIR/peerOrganizations/forensiclab.hot.coc.com/peers/peer0.forensiclab.hot.coc.com/tls/server.crt" "peer0.forensiclab TLS cert"
[ $? -eq 0 ] && ((valid_certs++))
((total_certs++))

verify_cert "$ORGANIZATIONS_DIR/peerOrganizations/forensiclab.hot.coc.com/users/Admin@forensiclab.hot.coc.com/msp/signcerts/cert.pem" "Admin@forensiclab"
[ $? -eq 0 ] && ((valid_certs++))
((total_certs++))

echo ""
echo "Verifying Archive Peer Certificates:"
verify_cert "$ORGANIZATIONS_DIR/peerOrganizations/archive.cold.coc.com/peers/peer0.archive.cold.coc.com/msp/signcerts/cert.pem" "peer0.archive signing cert"
[ $? -eq 0 ] && ((valid_certs++))
((total_certs++))

verify_cert "$ORGANIZATIONS_DIR/peerOrganizations/archive.cold.coc.com/peers/peer0.archive.cold.coc.com/tls/server.crt" "peer0.archive TLS cert"
[ $? -eq 0 ] && ((valid_certs++))
((total_certs++))

verify_cert "$ORGANIZATIONS_DIR/peerOrganizations/archive.cold.coc.com/users/Admin@archive.cold.coc.com/msp/signcerts/cert.pem" "Admin@archive"
[ $? -eq 0 ] && ((valid_certs++))
((total_certs++))

echo ""
echo "======================================================================"
echo "Verification Summary:"
echo "  Total certificates: $total_certs"
echo "  Valid certificates: $valid_certs"
echo "  Invalid certificates: $((total_certs - valid_certs))"
echo "======================================================================"

if [ $valid_certs -eq $total_certs ]; then
    echo "✓ All certificates are valid and signed by enclave Root CA"
    echo ""
    echo "Certificate chain verified successfully!"
    echo "All components are ready for mTLS communication."
    exit 0
else
    echo "❌ Some certificates are invalid"
    echo "   Regenerate certificates with: python3 generate_fabric_certs.py"
    exit 1
fi
